### ISSUE TITLE
lucene4.7和mmseg4j整合的时候高亮报错

### ISSUE THREAD

**Issue by leomx** [chenlb/mmseg4j-solr#10]
```
org.apache.lucene.search.highlight.InvalidTokenOffsetsException: Token ikanalyz exceeds length of provided text sized 79
    at org.apache.lucene.search.highlight.Highlighter.getBestTextFragments(Highlighter.java:225)
    at org.apache.lucene.search.highlight.Highlighter.getBestFragments(Highlighter.java:156)
    at org.apache.lucene.search.highlight.Highlighter.getBestFragment(Highlighter.java:102)
    at com.ifweb.web.search.SearchLogic.highlightFormat(SearchLogic.java:265)
    at com.ifweb.web.search.SearchLogic.addHits2List(SearchLogic.java:186)
    at com.ifweb.web.search.SearchLogic.getResult(SearchLogic.java:67)
    at com.ifweb.web.search.SearchLogic.main(SearchLogic.java:233)
Token ikanalyz exceeds length of provided text sized 79
```

求解答

**Comment by chenlb** [comment]
能提供一下索引前的内容和搜索的内容吗？
