### ISSUE TITLE
运行测试用例报 fix your classpath to have tests-framework.jar before lucene-core.jar

### ISSUE THREAD

**Issue by chenlb** [chenlb/mmseg4j-solr#7]
运行测试用例报 "java.lang.AssertionError: fix your classpath to have tests-framework.jar before lucene-core.jar" 错。

```
java.lang.AssertionError: fix your classpath to have tests-framework.jar before lucene-core.jar
	at __randomizedtesting.SeedInfo.seed([A21B138876C58AF1]:0)
	at org.apache.lucene.util.TestRuleSetupAndRestoreClassEnv.before(TestRuleSetupAndRestoreClassEnv.java:187)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:42)
	at com.carrotsearch.randomizedtesting.rules.SystemPropertiesInvariantRule$1.evaluate(SystemPropertiesInvariantRule.java:55)
```

**Comment by chenlb** [comment]
```xml
<dependency>
	  <groupId>org.apache.solr</groupId>
	  <artifactId>solr-test-framework</artifactId>
	  <version>${solr.version}</version>
	  <scope>test</scope>
</dependency>
```

(solr-test-framework 或 lucene-test-framework)配置放到依赖的顶部。
